### ISSUE TITLE
Adapter will be disabled after 10 unsuccessful connection attempts

### ISSUE THREAD

**Issue by Tottback** [iobroker-community-adapters/ioBroker.frontier_silicon#191]
After 10 unsuccessful connection attempts the adapter (v0.2.0) will be disabled. (Radio Medion Life P85044 / MD87180)
This could happen e.g. on router restart, Wifi problems etc.
Proposal to do a cyclic retry, e.g. every hour to reconnect, instead of disabling the adapter.

**Comment by pdbjjens** [comment]
@Tottback @mcm1957 
I think the proposal will improve the resilience of the adapter.
I will implement it next time when I touch the adapter (maybe as late as the 2025 maintenance release).

**Comment by pdbjjens** [comment]
Fixed in release v0.3.0
