### ISSUE TITLE
Update stable version in repo from 0.0.11 to 0.1.1

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.frontier_silicon#83]
# Think about update stable version to 0.1.1
**Version**: stable=**0.0.11** (143 days old) => latest=**0.1.1** (25 days old)
**Installs**: stable=**315** (43.81%), latest=**36** (5.01%), total=**719**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L701)

**Comment by pdbjjens** [comment]
@GermanBluefox 
I am still working on #46 . When it is fixed I will update the latest version to stable.

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 0.1.1 but the current stable version is already 0.1.1.

So this issue should be closed.
